from cube.cube_class import Cube
from cube.move_class import Move as M
from cube.moves import *


def generate_colour_symmetries(position):
    move_dict = {M.X: 'X ', M.NOT_X: "X'", M.X2: 'X2',
                 M.Y: 'Y ', M.NOT_Y: "Y'", M.Y2: 'Y2',
                 M.Z: 'Z ', M.NOT_Z: "Z'", M.Z2: 'Z2'}

    cube = Cube()
    not_z(cube)
    not_y(cube)
    print(cube.position)


"""

    WWWWWWWWWOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBYYYYYYYYY
    
    GGGGGGGGGOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWBBBBBBBBB # x
    YYYYYYYYYOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGWWWWWWWWW # x2
    BBBBBBBBBOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYGGGGGGGGG # x'
    
    WWWWWWWWWGGGRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBOOOYYYYYYYYY # y
    WWWWWWWWWRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGYYYYYYYYY # y2
    WWWWWWWWWBBBOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGRRRYYYYYYYYY # y'
    
    OOOOOOOOOYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBRRRRRRRRR # z
    YYYYYYYYYRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBWWWWWWWWW # z2
    RRRRRRRRRWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBOOOOOOOOO # z'
    
    GGGGGGGGGYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOBBBBBBBBB # x y
    GGGGGGGGGRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYBBBBBBBBB # x y2
    GGGGGGGGGWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRBBBBBBBBB # x y'
    
    OOOOOOOOOBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWRRRRRRRRR # x z
    BBBBBBBBBRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWGGGGGGGGG # x z2
    RRRRRRRRRGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWOOOOOOOOO # x z'
    
    YYYYYYYYYBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOWWWWWWWWW # x2 y
    YYYYYYYYYRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBWWWWWWWWW # x2 y2
    YYYYYYYYYGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRWWWWWWWWW # x2 y'
    
    OOOOOOOOOWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGRRRRRRRRR # x2 z
    WWWWWWWWWRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGYYYYYYYYY # x2 z2
    RRRRRRRRRYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGOOOOOOOOO # x2 z'
    
    BBBBBBBBBWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOGGGGGGGGG # x' y
    BBBBBBBBBRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWGGGGGGGGG # x' y2
    BBBBBBBBBYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRGGGGGGGGG # x' y'
    
    OOOOOOOOOGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYRRRRRRRRR # x' z
    GGGGGGGGGRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYBBBBBBBBB # x' z2
    RRRRRRRRRBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYOOOOOOOOO # x' z'
    
    RRRRRRRRRGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWOOOOOOOOO # y x
    YYYYYYYYYGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRWWWWWWWWW # y x2
    OOOOOOOOOGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYRRRRRRRRR # y x'
    
    GGGGGGGGGYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOBBBBBBBBB # y z
    YYYYYYYYYBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOWWWWWWWWW # y z2
    BBBBBBBBBWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOGGGGGGGGG # y z'
    
    BBBBBBBBBRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWGGGGGGGGG # y2 x
    YYYYYYYYYRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBWWWWWWWWW # y2 x2
    GGGGGGGGGRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYBBBBBBBBB # y2 x'
    
    RRRRRRRRRYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGOOOOOOOOO # y2 z
    YYYYYYYYYOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGWWWWWWWWW # y2 z2
    OOOOOOOOOWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGRRRRRRRRR # y2 z'
    
    OOOOOOOOOBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWRRRRRRRRR # y' x
    YYYYYYYYYBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOWWWWWWWWW # y' x2
    RRRRRRRRRBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYOOOOOOOOO # y' x'
    
    BBBBBBBBBYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRGGGGGGGGG # y' z
    YYYYYYYYYGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRWWWWWWWWW # y' z2
    GGGGGGGGGWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRBBBBBBBBB # y' z'
    
    GGGGGGGGGYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOBBBBBBBBB # z x
    RRRRRRRRRYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGOOOOOOOOO # z x2
    BBBBBBBBBYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRGGGGGGGGG # z x'
    
    OOOOOOOOOGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYRRRRRRRRR # z y
    OOOOOOOOOWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGRRRRRRRRR # z y2
    OOOOOOOOOBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWRRRRRRRRR # z y'
    
    GGGGGGGGGRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYBBBBBBBBB # z2 x
    WWWWWWWWWRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGYYYYYYYYY # z2 x2
    BBBBBBBBBRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWGGGGGGGGG # z2 x'
    
    YYYYYYYYYGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRWWWWWWWWW # z2 y
    YYYYYYYYYOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGWWWWWWWWW # z2 y2
    YYYYYYYYYBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOWWWWWWWWW # z2 y'
    
    GGGGGGGGGWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRBBBBBBBBB # z' x
    OOOOOOOOOWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGRRRRRRRRR # z' x2
    BBBBBBBBBWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOGGGGGGGGG # z' x'
    
    RRRRRRRRRGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWOOOOOOOOO # z' y
    RRRRRRRRRYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGOOOOOOOOO # z' y2
    RRRRRRRRRBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYOOOOOOOOO # z' y'

"""

"""

 
    BBBBBBBBBOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYGGGGGGGGG # x'                                 x'
    BBBBBBBBBRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWGGGGGGGGG # x z2 / x' y2 / y2 x / z2 x'        y2 x
    BBBBBBBBBWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOGGGGGGGGG # x' y / y z' / z' x'                x' y
    BBBBBBBBBYYYOOOWWWRRRYYYOOOWWWRRRYYYOOOWWWRRRGGGGGGGGG # x' y' / y' z / z x'                x' y'

    GGGGGGGGGOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWBBBBBBBBB # x                                  x
    GGGGGGGGGRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYBBBBBBBBB # x y2 / x' z2 / y2 x' / z2 x        x y2
    GGGGGGGGGWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRBBBBBBBBB # x y' / y' z' / z' x                x y'
    GGGGGGGGGYYYRRRWWWOOOYYYRRRWWWOOOYYYRRRWWWOOOBBBBBBBBB # x y / y z / z x                    x y

    OOOOOOOOOBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWRRRRRRRRR # x z / y' x / z y'                  x z
    OOOOOOOOOGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYRRRRRRRRR # x' z / y x' / z y                  x' z
    OOOOOOOOOWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGRRRRRRRRR # x2 z / y2 z' / z y2 / z' x2        x2 z
    OOOOOOOOOYYYGGGWWWBBBYYYGGGWWWBBBYYYGGGWWWBBBRRRRRRRRR # z                                  z

    RRRRRRRRRBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYOOOOOOOOO # x' z' / y' x' / z' y'              x' z'
    RRRRRRRRRGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWOOOOOOOOO # x z' / y x / z' y                  y x
    RRRRRRRRRWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBOOOOOOOOO # z'                                 z'
    RRRRRRRRRYYYBBBWWWGGGYYYBBBWWWGGGYYYBBBWWWGGGOOOOOOOOO # x2 z' / y2 z / z x2 / z' y2        y2 z
    
    WWWWWWWWWBBBOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGRRRYYYYYYYYY # y'                                 y'
    WWWWWWWWWGGGRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBOOOYYYYYYYYY # y                                  y
    WWWWWWWWWOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBYYYYYYYYY #                                    
    WWWWWWWWWRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGYYYYYYYYY # y2 / x2 z2 / z2 x2                 y2
    
    YYYYYYYYYBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOWWWWWWWWW # x2 y / y z2 / y' x2 / z2 y'        x2 y
    YYYYYYYYYGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRWWWWWWWWW # z2 / x2 y' / y x2 / y' z2 / z2 y   z2
    YYYYYYYYYOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGWWWWWWWWW # x2 / y2 z2 / z2 y2                 x2
    YYYYYYYYYRRRGGGOOOBBBRRRGGGOOOBBBRRRGGGOOOBBBWWWWWWWWW # x2 y2 / y2 x2                      x2 y2

"""
