del /S *.aux
del /S *.bbl
del /S *.blg
del /S *.lof
del /S *.log
del /S *.lot
del /S *.gz
del /S *.toc
del /S *.synctex(busy)
del /S Sheena.bib
del /S *.run.xml
del /S Dissertation-blx.bib
del /S *.out
del /S *.lol